name: playground2
on: push
env:
  IMAGE_BASENAME: 'my-app'
jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      # This action determines the container image tags for this build
      - name: Generate unique tag
        id: version-info
        run:  |
              REF_ID="${GITHUB_REF}"
              REF_ID="${REF_ID#refs/}"
              REF_ID="${REF_ID#heads/}"
              REF_ID="${REF_ID/pull\//pr-}"
              REF_ID="${REF_ID%/merge}"
              echo "::set-output name=image-tag::${REF_ID}-${GITHUB_RUN_NUMBER}-${GITHUB_SHA:0:8}"
        shell: bash
      - name: Docker Metadata Basic
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: foo/${{ env.IMAGE_BASENAME }}
      - name: Docker Metadata SemVer
#        if: github.ref != "refs/heads/${{ github.event.repository.default_branch }}"
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: foo/${{ env.IMAGE_BASENAME }}
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
            {{major}}
      - name: Docker Metadata for Master Build
#        if: github.ref == "refs/heads/${{ github.event.repository.default_branch }}"
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: foo/${{ env.IMAGE_BASENAME }}
          tag-custom: ${{ github.event.repository.default_branch }}-${{ github.run_number }}
          tag-custom-only: true
